filter:
    excluded_paths:
        - 'spec/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true

build:
    image: default-bionic
    nodes:
        analysis:
            environment:
                php: 8.1
                ini:
                    'xdebug.mode': 'coverage'
            tests:
                override:
                    - php-scrutinizer-run
        phpspec:
            environment:
                php: 8.1
                ini:
                    'xdebug.mode': 'coverage'
            tests:
                override:
                  - command: 'bin/phpspec run'
                    coverage:
                        file: 'coverage.xml'
                        format: 'php-clover'
